// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// This message defines the standard attribute vocabulary for Google APIs.
///
/// An attribute is a piece of metadata that describes an activity on a network
/// service. For example, the size of an HTTP request, or the status code of
/// an HTTP response.
///
/// Each attribute has a type and a name, which is logically defined as
/// a proto message field in `AttributeContext`. The field type becomes the
/// attribute type, and the field path becomes the attribute name. For example,
/// the attribute `source.ip` maps to field `AttributeContext.source.ip`.
///
/// This message definition is guaranteed not to have any wire breaking change.
/// So you can use it directly for passing attributes across different systems.
///
/// NOTE: Different system may generate different subset of attributes. Please
/// verify the system specification before relying on an attribute generated
/// a system.
public struct AttributeContext: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The origin of a network activity. In a multi hop network activity,
  /// the origin represents the sender of the first hop. For the first hop,
  /// the `source` and the `origin` must have the same content.
  public var origin: AttributeContext.Peer? = nil

  /// The source of a network activity, such as starting a TCP connection.
  /// In a multi hop network activity, the source represents the sender of the
  /// last hop.
  public var source: AttributeContext.Peer? = nil

  /// The destination of a network activity, such as accepting a TCP connection.
  /// In a multi hop network activity, the destination represents the receiver of
  /// the last hop.
  public var destination: AttributeContext.Peer? = nil

  /// Represents a network request, such as an HTTP request.
  public var request: AttributeContext.Request? = nil

  /// Represents a network response, such as an HTTP response.
  public var response: AttributeContext.Response? = nil

  /// Represents a target resource that is involved with a network activity.
  /// If multiple resources are involved with an activity, this must be the
  /// primary one.
  public var resource: AttributeContext.Resource? = nil

  /// Represents an API operation that is involved to a network activity.
  public var api: AttributeContext.Api? = nil

  /// Supports extensions for advanced use cases, such as logs and metrics.
  public var extensions: [GoogleCloudWkt.`Any`] = []

  /// Initialize a new instance of `AttributeContext`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AttributeContext().with { $0.origin = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// This message defines attributes for a node that handles a network request.
  /// The node can be either a service or an application that sends, forwards,
  /// or receives the request. Service peers should fill in
  /// `principal` and `labels` as appropriate.
  public struct Peer: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The IP address of the peer.
    public var ip: Swift.String = Swift.String()

    /// The network port of the peer.
    public var port: Swift.Int64 = Swift.Int64()

    /// The labels associated with the peer.
    public var labels: [Swift.String: Swift.String] = [:]

    /// The identity of this peer. Similar to `Request.auth.principal`, but
    /// relative to the peer instead of the request. For example, the
    /// identity associated with a load balancer that forwarded the request.
    public var principal: Swift.String = Swift.String()

    /// The CLDR country/region code associated with the above IP address.
    /// If the IP address is private, the `region_code` should reflect the
    /// physical location where this peer is running.
    public var regionCode: Swift.String = Swift.String()

    /// Initialize a new instance of `Peer`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Peer().with { $0.ip = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.rpc.context.AttributeContext.Peer"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// This message defines attributes associated with API operations, such as
  /// a network API request. The terminology is based on the conventions used
  /// by Google APIs, Istio, and OpenAPI.
  public struct Api: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The API service name. It is a logical identifier for a networked API,
    /// such as "pubsub.googleapis.com". The naming syntax depends on the
    /// API management system being used for handling the request.
    public var service: Swift.String = Swift.String()

    /// The API operation name. For gRPC requests, it is the fully qualified API
    /// method name, such as "google.pubsub.v1.Publisher.Publish". For OpenAPI
    /// requests, it is the `operationId`, such as "getPet".
    public var operation: Swift.String = Swift.String()

    /// The API protocol used for sending the request, such as "http", "https",
    /// "grpc", or "internal".
    public var `protocol`: Swift.String = Swift.String()

    /// The API version associated with the API operation above, such as "v1" or
    /// "v1alpha1".
    public var version: Swift.String = Swift.String()

    /// Initialize a new instance of `Api`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Api().with { $0.service = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case service = "service"
      case operation = "operation"
      case `protocol` = "protocol"
      case version = "version"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.service = try container.decode(Swift.String.self, forKey: .service)
      self.operation = try container.decode(Swift.String.self, forKey: .operation)
      self.`protocol` = try container.decode(Swift.String.self, forKey: .`protocol`)
      self.version = try container.decode(Swift.String.self, forKey: .version)
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.service, forKey: .service)
      try container.encode(self.operation, forKey: .operation)
      try container.encode(self.`protocol`, forKey: .`protocol`)
      try container.encode(self.version, forKey: .version)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.rpc.context.AttributeContext.Api"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// This message defines request authentication attributes. Terminology is
  /// based on the JSON Web Token (JWT) standard, but the terms also
  /// correlate to concepts in other standards.
  public struct Auth: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The authenticated principal. Reflects the issuer (`iss`) and subject
    /// (`sub`) claims within a JWT. The issuer and subject should be `/`
    /// delimited, with `/` percent-encoded within the subject fragment. For
    /// Google accounts, the principal format is:
    /// "https://accounts.google.com/{id}"
    public var principal: Swift.String = Swift.String()

    /// The intended audience(s) for this authentication information. Reflects
    /// the audience (`aud`) claim within a JWT. The audience
    /// value(s) depends on the `issuer`, but typically include one or more of
    /// the following pieces of information:
    ///
    /// *  The services intended to receive the credential. For example,
    ///    ["https://pubsub.googleapis.com/", "https://storage.googleapis.com/"].
    /// *  A set of service-based scopes. For example,
    ///    ["https://www.googleapis.com/auth/cloud-platform"].
    /// *  The client id of an app, such as the Firebase project id for JWTs
    ///    from Firebase Auth.
    ///
    /// Consult the documentation for the credential issuer to determine the
    /// information provided.
    public var audiences: [Swift.String] = []

    /// The authorized presenter of the credential. Reflects the optional
    /// Authorized Presenter (`azp`) claim within a JWT or the
    /// OAuth client id. For example, a Google Cloud Platform client id looks
    /// as follows: "123456789012.apps.googleusercontent.com".
    public var presenter: Swift.String = Swift.String()

    /// Structured claims presented with the credential. JWTs include
    /// `{key: value}` pairs for standard and private claims. The following
    /// is a subset of the standard required and optional claims that would
    /// typically be presented for a Google-based JWT:
    ///
    ///    {'iss': 'accounts.google.com',
    ///     'sub': '113289723416554971153',
    ///     'aud': ['123456789012', 'pubsub.googleapis.com'],
    ///     'azp': '123456789012.apps.googleusercontent.com',
    ///     'email': 'jsmith@example.com',
    ///     'iat': 1353601026,
    ///     'exp': 1353604926}
    ///
    /// SAML assertions are similarly specified, but with an identity provider
    /// dependent structure.
    public var claims: GoogleCloudWkt.Struct? = nil

    /// A list of access level resource names that allow resources to be
    /// accessed by authenticated requester. It is part of Secure GCP processing
    /// for the incoming request. An access level string has the format:
    /// "//{api_service_name}/accessPolicies/{policy_id}/accessLevels/{short_name}"
    ///
    /// Example:
    /// "//accesscontextmanager.googleapis.com/accessPolicies/MY_POLICY_ID/accessLevels/MY_LEVEL"
    public var accessLevels: [Swift.String] = []

    /// Initialize a new instance of `Auth`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Auth().with { $0.principal = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.rpc.context.AttributeContext.Auth"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// This message defines attributes for an HTTP request. If the actual
  /// request is not an HTTP request, the runtime system should try to map
  /// the actual request to an equivalent HTTP request.
  public struct Request: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The unique ID for a request, which can be propagated to downstream
    /// systems. The ID should have low probability of collision
    /// within a single day for a specific service.
    public var id: Swift.String = Swift.String()

    /// The HTTP request method, such as `GET`, `POST`.
    public var method: Swift.String = Swift.String()

    /// The HTTP request headers. If multiple headers share the same key, they
    /// must be merged according to the HTTP spec. All header keys must be
    /// lowercased, because HTTP header keys are case-insensitive.
    public var headers: [Swift.String: Swift.String] = [:]

    /// The HTTP URL path, excluding the query parameters.
    public var path: Swift.String = Swift.String()

    /// The HTTP request `Host` header value.
    public var host: Swift.String = Swift.String()

    /// The HTTP URL scheme, such as `http` and `https`.
    public var scheme: Swift.String = Swift.String()

    /// The HTTP URL query in the format of `name1=value1&name2=value2`, as it
    /// appears in the first line of the HTTP request. No decoding is performed.
    public var query: Swift.String = Swift.String()

    /// The timestamp when the `destination` service receives the last byte of
    /// the request.
    public var time: GoogleCloudWkt.Timestamp? = nil

    /// The HTTP request size in bytes. If unknown, it must be -1.
    public var size: Swift.Int64 = Swift.Int64()

    /// The network protocol used with the request, such as "http/1.1",
    /// "spdy/3", "h2", "h2c", "webrtc", "tcp", "udp", "quic". See
    /// https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids
    /// for details.
    public var `protocol`: Swift.String = Swift.String()

    /// A special parameter for request reason. It is used by security systems
    /// to associate auditing information with a request.
    public var reason: Swift.String = Swift.String()

    /// The request authentication. May be absent for unauthenticated requests.
    /// Derived from the HTTP request `Authorization` header or equivalent.
    public var auth: AttributeContext.Auth? = nil

    /// The values from Origin header from the HTTP request, such as
    /// "https://console.cloud.google.com". Modern browsers can only have one
    /// origin. Special browsers and/or HTTP clients may require multiple
    /// origins.
    public var origin: Swift.String = Swift.String()

    /// Initialize a new instance of `Request`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Request().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case id = "id"
      case method = "method"
      case headers = "headers"
      case path = "path"
      case host = "host"
      case scheme = "scheme"
      case query = "query"
      case time = "time"
      case size = "size"
      case `protocol` = "protocol"
      case reason = "reason"
      case auth = "auth"
      case origin = "origin"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.id = try container.decode(Swift.String.self, forKey: .id)
      self.method = try container.decode(Swift.String.self, forKey: .method)
      self.headers = try container.decode([Swift.String: Swift.String].self, forKey: .headers)
      self.path = try container.decode(Swift.String.self, forKey: .path)
      self.host = try container.decode(Swift.String.self, forKey: .host)
      self.scheme = try container.decode(Swift.String.self, forKey: .scheme)
      self.query = try container.decode(Swift.String.self, forKey: .query)
      self.time = try container.decodeIfPresent(GoogleCloudWkt.Timestamp.self, forKey: .time)
      self.size = try container.decode(Swift.Int64.self, forKey: .size)
      self.`protocol` = try container.decode(Swift.String.self, forKey: .`protocol`)
      self.reason = try container.decode(Swift.String.self, forKey: .reason)
      self.auth = try container.decodeIfPresent(AttributeContext.Auth.self, forKey: .auth)
      self.origin = try container.decode(Swift.String.self, forKey: .origin)
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.id, forKey: .id)
      try container.encode(self.method, forKey: .method)
      try container.encode(self.headers, forKey: .headers)
      try container.encode(self.path, forKey: .path)
      try container.encode(self.host, forKey: .host)
      try container.encode(self.scheme, forKey: .scheme)
      try container.encode(self.query, forKey: .query)
      try container.encode(self.time, forKey: .time)
      try container.encode(self.size, forKey: .size)
      try container.encode(self.`protocol`, forKey: .`protocol`)
      try container.encode(self.reason, forKey: .reason)
      try container.encode(self.auth, forKey: .auth)
      try container.encode(self.origin, forKey: .origin)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.rpc.context.AttributeContext.Request"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// This message defines attributes for a typical network response. It
  /// generally models semantics of an HTTP response.
  public struct Response: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The HTTP response status code, such as `200` and `404`.
    public var code: Swift.Int64 = Swift.Int64()

    /// The HTTP response size in bytes. If unknown, it must be -1.
    public var size: Swift.Int64 = Swift.Int64()

    /// The HTTP response headers. If multiple headers share the same key, they
    /// must be merged according to HTTP spec. All header keys must be
    /// lowercased, because HTTP header keys are case-insensitive.
    public var headers: [Swift.String: Swift.String] = [:]

    /// The timestamp when the `destination` service sends the last byte of
    /// the response.
    public var time: GoogleCloudWkt.Timestamp? = nil

    /// The amount of time it takes the backend service to fully respond to a
    /// request. Measured from when the destination service starts to send the
    /// request to the backend until when the destination service receives the
    /// complete response from the backend.
    public var backendLatency: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `Response`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Response().with { $0.code = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.rpc.context.AttributeContext.Response"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// This message defines core attributes for a resource. A resource is an
  /// addressable (named) entity provided by the destination service. For
  /// example, a file stored on a network storage service.
  public struct Resource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The name of the service that this resource belongs to, such as
    /// `pubsub.googleapis.com`. The service may be different from the DNS
    /// hostname that actually serves the request.
    public var service: Swift.String = Swift.String()

    /// The stable identifier (name) of a resource on the `service`. A resource
    /// can be logically identified as "//{resource.service}/{resource.name}".
    /// The differences between a resource name and a URI are:
    ///
    /// *   Resource name is a logical identifier, independent of network
    ///     protocol and API version. For example,
    ///     `//pubsub.googleapis.com/projects/123/topics/news-feed`.
    /// *   URI often includes protocol and version information, so it can
    ///     be used directly by applications. For example,
    ///     `https://pubsub.googleapis.com/v1/projects/123/topics/news-feed`.
    ///
    /// See https://cloud.google.com/apis/design/resource_names for details.
    public var name: Swift.String = Swift.String()

    /// The type of the resource. The syntax is platform-specific because
    /// different platforms define their resources differently.
    ///
    /// For Google APIs, the type format must be "{service}/{kind}", such as
    /// "pubsub.googleapis.com/Topic".
    public var type: Swift.String = Swift.String()

    /// The labels or tags on the resource, such as AWS resource tags and
    /// Kubernetes resource labels.
    public var labels: [Swift.String: Swift.String] = [:]

    /// The unique identifier of the resource. UID is unique in the time
    /// and space for this resource within the scope of the service. It is
    /// typically generated by the server on successful creation of a resource
    /// and must not be changed. UID is used to uniquely identify resources
    /// with resource name reuses. This should be a UUID4.
    public var uid: Swift.String = Swift.String()

    /// Annotations is an unstructured key-value map stored with a resource that
    /// may be set by external tools to store and retrieve arbitrary metadata.
    /// They are not queryable and should be preserved when modifying objects.
    ///
    /// More info:
    /// https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    public var annotations: [Swift.String: Swift.String] = [:]

    /// Mutable. The display name set by clients. Must be <= 63 characters.
    public var displayName: Swift.String = Swift.String()

    /// Output only. The timestamp when the resource was created. This may
    /// be either the time creation was initiated or when it was completed.
    public var createTime: GoogleCloudWkt.Timestamp? = nil

    /// Output only. The timestamp when the resource was last updated. Any
    /// change to the resource made by users must refresh this value.
    /// Changes to a resource made by the service should refresh this value.
    public var updateTime: GoogleCloudWkt.Timestamp? = nil

    /// Output only. The timestamp when the resource was deleted.
    /// If the resource is not deleted, this must be empty.
    public var deleteTime: GoogleCloudWkt.Timestamp? = nil

    /// Output only. An opaque value that uniquely identifies a version or
    /// generation of a resource. It can be used to confirm that the client
    /// and server agree on the ordering of a resource being written.
    public var etag: Swift.String = Swift.String()

    /// Immutable. The location of the resource. The location encoding is
    /// specific to the service provider, and new encoding may be introduced
    /// as the service evolves.
    ///
    /// For Google Cloud products, the encoding is what is used by Google Cloud
    /// APIs, such as `us-east1`, `aws-us-east-1`, and `azure-eastus2`. The
    /// semantics of `location` is identical to the
    /// `cloud.googleapis.com/location` label used by some Google Cloud APIs.
    public var location: Swift.String = Swift.String()

    /// Initialize a new instance of `Resource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Resource().with { $0.service = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.rpc.context.AttributeContext.Resource"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.rpc.context.AttributeContext"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
