// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// `AuditContext` provides information that is needed for audit logging.
public struct AuditContext: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Serialized audit log.
  public var auditLog: Foundation.Data = Foundation.Data()

  /// An API request message that is scrubbed based on the method annotation.
  /// This field should only be filled if audit_log field is present.
  /// Service Control will use this to assemble a complete log for Cloud Audit
  /// Logs and Google internal audit logs.
  public var scrubbedRequest: GoogleWKT.Struct? = nil

  /// An API response message that is scrubbed based on the method annotation.
  /// This field should only be filled if audit_log field is present.
  /// Service Control will use this to assemble a complete log for Cloud Audit
  /// Logs and Google internal audit logs.
  public var scrubbedResponse: GoogleWKT.Struct? = nil

  /// Number of scrubbed response items.
  public var scrubbedResponseItemCount: Swift.Int32 = Swift.Int32()

  /// Audit resource name which is scrubbed.
  public var targetResource: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AuditContext`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuditContext().with { $0.auditLog = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let auditLog = CodingKeys(stringValue: "auditLog")
    static let scrubbedRequest = CodingKeys(stringValue: "scrubbedRequest")
    static let scrubbedResponse = CodingKeys(stringValue: "scrubbedResponse")
    static let scrubbedResponseItemCount = CodingKeys(stringValue: "scrubbedResponseItemCount")
    static let targetResource = CodingKeys(stringValue: "targetResource")

    static let _knownKeys: Set<Swift.String> = [
      "auditLog",
      "scrubbedRequest",
      "scrubbedResponse",
      "scrubbedResponseItemCount",
      "targetResource",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .auditLog) {
      self.auditLog = value
    }
    self.scrubbedRequest = try container.decodeIfPresent(
      GoogleWKT.Struct.self, forKey: .scrubbedRequest)
    self.scrubbedResponse = try container.decodeIfPresent(
      GoogleWKT.Struct.self, forKey: .scrubbedResponse)
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .scrubbedResponseItemCount)
    {
      self.scrubbedResponseItemCount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .targetResource) {
      self.targetResource = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.auditLog, forKey: .auditLog)
    try container.encodeIfPresent(self.scrubbedRequest, forKey: .scrubbedRequest)
    try container.encodeIfPresent(self.scrubbedResponse, forKey: .scrubbedResponse)
    try container.encode(self.scrubbedResponseItemCount, forKey: .scrubbedResponseItemCount)
    try container.encode(self.targetResource, forKey: .targetResource)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.rpc.context.AuditContext"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
