// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// `AuditContext` provides information that is needed for audit logging.
public struct AuditContext: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Serialized audit log.
  public var auditLog: Foundation.Data = Foundation.Data()

  /// An API request message that is scrubbed based on the method annotation.
  /// This field should only be filled if audit_log field is present.
  /// Service Control will use this to assemble a complete log for Cloud Audit
  /// Logs and Google internal audit logs.
  public var scrubbedRequest: GoogleCloudWKT.Struct? = nil

  /// An API response message that is scrubbed based on the method annotation.
  /// This field should only be filled if audit_log field is present.
  /// Service Control will use this to assemble a complete log for Cloud Audit
  /// Logs and Google internal audit logs.
  public var scrubbedResponse: GoogleCloudWKT.Struct? = nil

  /// Number of scrubbed response items.
  public var scrubbedResponseItemCount: Swift.Int32 = Swift.Int32()

  /// Audit resource name which is scrubbed.
  public var targetResource: Swift.String = Swift.String()

  /// Initialize a new instance of `AuditContext`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuditContext().with { $0.auditLog = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.rpc.context.AuditContext"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
